### ISSUE TITLE
Hidding the Menu after clicking on one item

### ISSUE THREAD

**Issue by shadialtarsha** [dericgw/react-tiny-fab#18]
Hello, Can I trigger the mouseleave event after I click on one of the menu items. Currently, I am opening a dialog after clicking on the first item in the menu but the state of the FAB not changing from open true to open false. I tried to trigger the mouseleave (mouseout) events from the code but no success. My goal is just hide the menu after clicking on any of the items in the menu

**Comment by dericgw** [comment]
Can you paste the exact code you’re using so I can find a solution?

**Comment by shadialtarsha** [comment]
Thank you for replaying
my FAB code: 
`const FloatingActionButton = ({ actions }) => (
  <Fab
    mainButtonStyles={{ backgroundColor: '#00bcd4' }}
    position={{
      bottom: 0,
      right: '0.5rem',
    }}
    icon={<i className="zmdi zmdi-settings zmdi-hc-lg" />}
    event="hover"
  >
    {actions.map(action => (
      <Action
        key={Math.random()}
        style={{ backgroundColor: '#00bcd4' }}
        text={action.text}
        onClick={action.handleOnClick}
      >
        <i className={action.icon} />
      </Action>
    ))}
  </Fab>
);`

`
import React from 'react';
import { connect } from 'react-redux';
import { withRouter } from 'react-router-dom';
import ContainerHeader from '../ContainerHeader';
import Loader from '../Loader';
import Toast from '../Toast';
import AdminsList from './AdminsList';
import Fab from '../FloatingActionButton';
import AddDialog from './AddDialog';
import IntlMessages from '../../util/IntlMessages';
import { showAdminsLoader, setAdmins, resetAdminsFaliure } from '../../actions/Admins';

class Admins extends React.Component {
  state = {
    isAddDialogOpen: false,
  };

  componentDidMount() {
    const { authToken, dispatchSetAdmins, dispatchShowAdminsLoader } = this.props;
    dispatchShowAdminsLoader();
    dispatchSetAdmins(authToken);
  }

  componentDidUpdate() {
    const { faliure, dispatchResetAdminsFaliure } = this.props;
    if (faliure) {
      setTimeout(() => {
        dispatchResetAdminsFaliure();
      }, 2300);
    }
  }

  handleOpenAddDialog = () => {
    this.setState(() => ({ isAddDialogOpen: true }));
  };

  handleCloseAddDialog = () => {
    this.setState(() => ({ isAddDialogOpen: false }));
  };

  render() {
    const { isAddDialogOpen } = this.state;
    const { adminsList, faliure, message, loader, match } = this.props;
    return (
      <React.Fragment>
        {loader && <Loader />}
        {faliure && <Toast type="error" message={message} />}
        <div className="app-wrapper">
          <div className="animated slideInUpTiny animation-duration-3">
            <ContainerHeader match={match} title={<IntlMessages id="sidebar.adminManagement" />} />
            <div className="row mb-md-4">
              <div className="col-12">
                <div className="jr-card">
                  <AdminsList admins={adminsList} />
                </div>
              </div>
            </div>
          </div>
        </div>
        <Fab
          actions={[
            {
              text: 'New Admin',
              handleOnClick: this.handleOpenAddDialog,
              icon: 'zmdi zmdi-account-add',
            },
          ]}
        />
        <AddDialog isOpen={isAddDialogOpen} handleRequestClose={this.handleCloseAddDialog} />
      </React.Fragment>
    );
  }
}
`

**Comment by shadialtarsha** [comment]
Thank you for replaying
my FAB code: 
```
const FloatingActionButton = ({ actions }) => (
  <Fab
    mainButtonStyles={{ backgroundColor: '#00bcd4' }}
    position={{
      bottom: 0,
      right: '0.5rem',
    }}
    icon={<i className="zmdi zmdi-settings zmdi-hc-lg" />}
    event="hover"
  >
    {actions.map(action => (
      <Action
        key={Math.random()}
        style={{ backgroundColor: '#00bcd4' }}
        text={action.text}
        onClick={action.handleOnClick}
      >
        <i className={action.icon} />
      </Action>
    ))}
  </Fab>
);
```
Here I am using it:
```
import React from 'react';
import { connect } from 'react-redux';
import { withRouter } from 'react-router-dom';
import ContainerHeader from '../ContainerHeader';
import Loader from '../Loader';
import Toast from '../Toast';
import AdminsList from './AdminsList';
import Fab from '../FloatingActionButton';
import AddDialog from './AddDialog';
import IntlMessages from '../../util/IntlMessages';
import { showAdminsLoader, setAdmins, resetAdminsFaliure } from '../../actions/Admins';

class Admins extends React.Component {
  state = {
    isAddDialogOpen: false,
  };

  componentDidMount() {
    const { authToken, dispatchSetAdmins, dispatchShowAdminsLoader } = this.props;
    dispatchShowAdminsLoader();
    dispatchSetAdmins(authToken);
  }

  componentDidUpdate() {
    const { faliure, dispatchResetAdminsFaliure } = this.props;
    if (faliure) {
      setTimeout(() => {
        dispatchResetAdminsFaliure();
      }, 2300);
    }
  }

  handleOpenAddDialog = () => {
    this.setState(() => ({ isAddDialogOpen: true }));
  };

  handleCloseAddDialog = () => {
    this.setState(() => ({ isAddDialogOpen: false }));
  };

  render() {
    const { isAddDialogOpen } = this.state;
    const { adminsList, faliure, message, loader, match } = this.props;
    return (
      <React.Fragment>
        {loader && <Loader />}
        {faliure && <Toast type="error" message={message} />}
        <div className="app-wrapper">
          <div className="animated slideInUpTiny animation-duration-3">
            <ContainerHeader match={match} title={<IntlMessages id="sidebar.adminManagement" />} />
            <div className="row mb-md-4">
              <div className="col-12">
                <div className="jr-card">
                  <AdminsList admins={adminsList} />
                </div>
              </div>
            </div>
          </div>
        </div>
        <Fab
          actions={[
            {
              text: 'New Admin',
              handleOnClick: this.handleOpenAddDialog,
              icon: 'zmdi zmdi-account-add',
            },
          ]}
        />
        <AddDialog isOpen={isAddDialogOpen} handleRequestClose={this.handleCloseAddDialog} />
      </React.Fragment>
    );
  }
}
const mapStateToProps = ({ auth, admins }) => {
  const { authToken } = auth;
  const { admins: adminsList, faliure, message, loader } = admins;
  return { authToken, adminsList, faliure, message, loader };
};

export default withRouter(
  connect(
    mapStateToProps,
    {
      dispatchSetAdmins: setAdmins,
      dispatchResetAdminsFaliure: resetAdminsFaliure,
      dispatchShowAdminsLoader: showAdminsLoader,
    }
  )(Admins)
);
```
So I want after opening the AddDialog i want the fab menu to be closed.
Currently, AddDialog is open by the FAB

**Comment by dericgw** [comment]
@shadialtarsha I put a fix in place that should address this. Make sure to update your package.json to use v2 of `react-tiny-fab` and let me know if that fixes the issue for you.

**Comment by shadialtarsha** [comment]
@dericgw Thank you so much. It works perfectly

**Comment by dericgw** [comment]
@shadialtarsha So good to hear!
