### ISSUE TITLE
I need type definition

### ISSUE THREAD

**Issue by NoMoreViolence** [dericgw/react-tiny-fab#22]
I use typescript react,
But, there is no any type definition
can you support for typescript react users?

**Comment by NoMoreViolence** [comment]
Maybe I can make type definition for your library

**Comment by dericgw** [comment]
That would be great!

**Comment by NoMoreViolence** [comment]
I pushed type definition

**Comment by dericgw** [comment]
Type definitions are now live in v3 🎉
