### ISSUE TITLE
Home page update

### ISSUE THREAD

**Issue by NoMoreViolence** [dericgw/react-tiny-fab#23]
https://dericgw.github.io/react-tiny-fab/#/

This part need to change.

Usage
There are two components available for import - Fab and Action. You import them like this:

1
   import { Fab, Action } from 'react-tiny-fab';
2
 ###   import 'react-tiny-fab/styles.css';
to
 ###   import 'react-tiny-fab/dist/styles.css';

The description between github README and homepage is different.

The github document you wrote is correct.

**Comment by dericgw** [comment]
@NoMoreViolence This will be fixed with the next version which I am about to release. Thanks for pointing this out!
