### ISSUE TITLE
Add an option to control whether the title of the button is displayed

### ISSUE THREAD

**Issue by ettingshausen** [dericgw/react-tiny-fab#26]
The title of the button shown only if when it was hoverd. These buttons are not easily hovered if used on a mobile  situation.
So, are we considering adding an option to control whether the title is displayed not only the button is hovered?

**Comment by ettingshausen** [comment]
I added the option.
Using like this:
```jsx
<Fab
            mainButtonStyles={{ backgroundColor: '#304FFE' }}
            position={{ bottom: 0, right: 0 }}
            icon={<MdAdd />}
            event='click'
            key='1'
            showTitle={true}
        >
```
![gifhome_360x566](https://user-images.githubusercontent.com/9806325/60435555-7b2c9180-9c3c-11e9-9504-edd3762abf42.gif)

To keep the original look, just remove the `showTitle` prop.

**Comment by dericgw** [comment]
Version 3 is now released and this fix is live 🎉  Thanks for your help with this.
