### ISSUE TITLE
Add docz so that there is interactive documentation

### ISSUE THREAD

**Issue by dericgw** [dericgw/react-tiny-fab#3]
I would like to add https://github.com/pedronauck/docz to the lib so that I can have a Gitub pages page with interactive documentation.

**Comment by d-ivashchuk** [comment]
hey @dericgw, do you need to transfer current `Readme` to docz or just to add it to the project?

**Comment by dericgw** [comment]
@d-ivashchuk Hey! I do not want to replace the current readme. Instead, I would like to add Docz and setup the FAB as a component within Docz. Also, it would be great to get the `PropsTable` working. This does not have to be exhaustive because I will tweak it later.

Does that make sense? Let me know if you need more clarification.

**Comment by d-ivashchuk** [comment]
I've previously worked with `react-styleguidist` but I think I can handle  `docz` also  for the learning purposes. The question is, will you deploy it somewhere else, or you need a way to integrate `docz` documentation to github?

**Comment by d-ivashchuk** [comment]
Anyway, I will start working on this and see where it leads us!

**Comment by dericgw** [comment]
When specifically are you looking to do? You can find the example within the `./example` folder. That is, essentially, just a Create React App project that displays the FAB in various different ways. When you run `npm start`, it should open the browser for you.

**Comment by d-ivashchuk** [comment]
Nah, does not open a browser for some reason, and that's why I was asking for specific path:)

**Comment by dericgw** [comment]
Did you figure it out? Are you on a Mac, or something else?

**Comment by d-ivashchuk** [comment]
No, I've decided to try the component out in `docz` directly but having no luck so far to make it work. That's where dev tools would help. Yeah, I am on mac and I'm getting the following console output on npm start `created example/src/fab.js in 1s`

**Comment by dericgw** [comment]
Try this...
```bash
cd example && npm i && cd .. && npm start
```

I am thinking that maybe the deps did not get installed in the `example` folder.

**Comment by d-ivashchuk** [comment]
Yep, probably my bad! now it's working, I will submit a PR when I will make it work

**Comment by dericgw** [comment]
@d-ivashchuk Thanks for working on this for me! I am going to accept the PR. I will play around with it and I may use it as my dev environment if it seems like a good fit for such. Anyhow, thanks again.

**Comment by dericgw** [comment]
Closed by #4
