### ISSUE TITLE
Allow className props

### ISSUE THREAD

**Issue by YassienW** [dericgw/react-tiny-fab#30]
Is there a reason to why we can't do that? It would be handy for people who don't use React styles.

**Comment by dericgw** [comment]
The problem is that there are multiple components and if I allow the class name prop, what component should that apply to? What is your specific use case and maybe I can help you?

**Comment by YassienW** [comment]
From my understanding you allow the style prop on the `<Fab/>` and the `<Action/>` components. Allowing a className prop would allow styling the same components via a css class instead of having to use inline styles, it wouldn't be much different. It can be further extended by adding props for their respective elements, but this is not something that the library offers right now anyway. For my use case i would like to extensively style the components with css classes i already have, but even if i didn't i prefer keeping my css rules in an external file. The issue can be closed since I've found an alternative Fab library that is more suitable to that need, but i think this should be implemented since people are more used to using classes than inline styles anyway.

**Comment by dericgw** [comment]
All of the components have a `className` already, so you could style them any way you want using an external stylesheet, Styled Components, etc. That is something that I should document better so that people have a better understanding of the different ways to style the components.

**Comment by YassienW** [comment]
I realize that this is a possible option, however if i have pre-existing classes that i would like to apply to a component, it would be far more convenient and cleaner to simply add the classes to said component, rather than manually copy all the styles. This is especially true if you are using a class from an external component library like Bootstrap (which i am).

**Comment by mathiscode** [comment]
+1 on this - I wanted to use [animate.css](https://animate.style) and this was a stumbling block.

**Comment by dericgw** [comment]
@mathiscode This should work in the new version. Have you tried it?

**Comment by mathiscode** [comment]
> 
> 
> @mathiscode This should work in the new version. Have you tried it?

Yikes! You made me realize I was using an outdated version. :smile:

It does work, but when I specify the className prop to <Fab>, I lose the automatic open/close handling and I have to manually include the rtf class and also handle clicks to swap the open/closed classes.

```
          className='rtf closed animate__animated animate__infinite animate__slower animate__bounce'
          onClick={e => {
            const container = document.querySelector('ul.rtf')

            if (Array.from(container.classList).includes('closed')) {
              container.classList.remove('closed')
              container.classList.add('open')
            } else {
              container.classList.remove('open')
              container.classList.add('closed')
            }
          }}
```
