### ISSUE TITLE
Clicking on iOS device in Safari and Chrome not working

### ISSUE THREAD

**Issue by tameem92** [dericgw/react-tiny-fab#31]
Hi, 

I've been trying to test tiny-fab on an iOS device. And only the first click sometimes works on Safari, but then no click events are fired. I see a similar issue in Chrome on iPhone X as well. 

Has anyone run into this issue? Also, what other information should I provide to dig into it more?

**Comment by dericgw** [comment]
I can confirm this is happening on my Google Pixel as well (Chrome). Do you have the event prop set to "hover"?

**Comment by tameem92** [comment]
I've tried changing it to 'click' as well. Seeing the same issue with both. I will try and dig into it a bit deeper today.

**Comment by tameem92** [comment]
I just tried the example in the project. And seems to be like the "click" events are working on the iOS device. Going to try that in my project and make sure it's actually following the click event.

**Comment by tameem92** [comment]
Changing the event to "click" solves the issue. I am just switching based on screen size with even type to use. Going to close the issue.
