### ISSUE TITLE
Missing type definition

### ISSUE THREAD

**Issue by ymkz** [dericgw/react-tiny-fab#34]
##### Issue
#22 is pushed type definition into this repo, but npm published module has not `d.ts` file.

##### Reason
The reason is that the package.json `types` field specifies `src/index.d.ts`, but the `src`  directory is not included in publish.

##### Suggestion
I think it can be solve by either.
- Include `src` directory to publish with `files` field in package.json.
- Deploy `index.d.ts` to `dist` directory.

What do you think?

**Comment by dericgw** [comment]
@ymkz Thanks for pointing this out. I am copying the types file on build now and I updated the package.json to reflect the location of the types file in `v3.0.2`.

**Comment by ymkz** [comment]
@dericgw Great work! Thank you.
