### ISSUE TITLE
Clicking on an input field "minimizes" the button

### ISSUE THREAD

**Issue by cheles** [dericgw/react-tiny-fab#35]
Hello
I've been testing your sample from here https://github.com/dericgw/react-tiny-fab/blob/master/example/index.html with <Help /> component. It seems that as soon as I click in one of the inputs, the form dissapears. Is there a workaround for that? 

Thanks

**Comment by dericgw** [comment]
@cheles So sorry for the delay. I will look into this and get a fix out.

**Comment by dericgw** [comment]
This will be fixed in v4 which is about to be released.
