### ISSUE TITLE
Add speed animation control

### ISSUE THREAD

**Issue by velthune** [dericgw/react-tiny-fab#38]
Hi Deric, nice component so thank a lot to share it!
It would be nice if you will add a prop to setup the animation speed of the appearing actions 😇

**Comment by dericgw** [comment]
Thanks!! As of right now, the animation is handled by CSS. I would have to jump through a couple of hoops to make it allow for transition times. You could override the CSS if you want to change it. https://github.com/dericgw/react-tiny-fab/blob/898528d034762c42d218fdddf34b14427d1d4ff6/src/styles.scss#L35
