### ISSUE TITLE
Use the FAB without menu

### ISSUE THREAD

**Issue by shanhuiyang** [dericgw/react-tiny-fab#40]
Thanks for this good widget.
Sometimes I just have one action to add into the FAB. 
Then I do not want to expand the menu while user click the FAB; instead I want directly take the action while user click the FAB. 
It seems like I have no way to do that.
Could you please support that. I think we can just add an onClick property so that FAB can take the onClick action directly.

**Comment by dericgw** [comment]
@shanhulyang I added an `onClick` prop to the main button and published to NPM so this should work now.

**Comment by shanhuiyang** [comment]
@dericgw This is great! Love you guys.

**Comment by shanhuiyang** [comment]
I just tested 3.1.0. I found following issues that may be improved.
1. When `onClick` for `<Fab/>` is enabled, the icon should not spin with an angle. It should act exactly like `<Action/>` do.
2. When `onClick` for `<Fab/>` is enabled, text can be shown while mouse hover on `<Fab/>`, just like `<Action/>` do. Therefore, one more property can be added into 
3. Update [index.d.ts](https://github.com/dericgw/react-tiny-fab/blob/master/src/index.d.ts) for Typescript users.

Thank you!

**Comment by dericgw** [comment]
Feel free to open a PR with the suggested changes!

Deric Cain

________________________________

**Comment by shanhuiyang** [comment]
@dericgw https://github.com/dericgw/react-tiny-fab/pull/43/files

**Comment by shanhuiyang** [comment]
@dericgw gently ping.

**Comment by Exter-dg** [comment]
> @dericgw https://github.com/dericgw/react-tiny-fab/pull/43/files

I am unable to display text on hover while using onClick unless I set `alwaysShowTitle` to `true` where it stays on the screen always(even when the user is not hovering).
Also, any way to change the CSS on hover when onClick is enabled on Fab?
