### ISSUE TITLE
Fab cannot float correctly while the window is narrow

### ISSUE THREAD

**Issue by shanhuiyang** [dericgw/react-tiny-fab#41]
For example on the mobile browser the FAB is stick to the bottom of the layout but not float.
If this is bug? In desktop browser the FAB is works very well. I think this issue is easy to reproduce.
## 

It looks like I am doing something wrong but I don't know what's is wrong...
The example FAB looks good on mobile browser.

**Comment by dericgw** [comment]
[The position is fixed](https://github.com/dericgw/react-tiny-fab/blob/master/src/styles.scss#L4), so I am not sure what is going on. Can you show some reproducible code?

**Comment by shanhuiyang** [comment]
Let me extract to some example code, **will attach it later**.

**Comment by shanhuiyang** [comment]
I used react-tiny-fab in one of [my repo](https://github.com/shanhuiyang/TypeScript-MERN-Starter).
I created a component named [`MenuFab`](https://github.com/shanhuiyang/TypeScript-MERN-Starter/blob/master/client/core/src/components/shared/MenuFab.tsx). Just abstract the properties into objects.
Then I used this component [in a page](https://github.com/shanhuiyang/TypeScript-MERN-Starter/blob/master/client/core/src/components/article/ArticleList.tsx#L73), just passing some property objects into it.
Finally I render this in a [semantic-ui-react](https://react.semantic-ui.com/) component [`Container`](https://github.com/shanhuiyang/TypeScript-MERN-Starter/blob/master/client/core/src/components/article/ArticleList.tsx#L39).

To illustrate the issue, attached some screenshots.
1. in desktop it works fine.
<img width="1435" alt="Screen Shot 2019-11-27 at 4 41 31 PM" src="https://user-images.githubusercontent.com/50712413/69718699-069b4780-1135-11ea-92e1-ef92447d9a39.png">
2. in narrow window (to mimic the mobile browser), the fab disappear.
<img width="530" alt="Screen Shot 2019-11-27 at 4 42 09 PM" src="https://user-images.githubusercontent.com/50712413/69718750-216dbc00-1135-11ea-9c2d-ec6878282f4a.png">
3. indeed it sticks to the bottom of the page, is not floating now.
<img width="530" alt="Screen Shot 2019-11-27 at 4 42 24 PM" src="https://user-images.githubusercontent.com/50712413/69718831-43673e80-1135-11ea-8807-2c91fc698bef.png">

I thought I have made some mistakes because in your document page there is not such issue.

**Comment by dericgw** [comment]
I would like to see the dev tools and check out the element to see if some style is being overwritten. If you look at the docs page of this library and change the width to mimic mobile, you'll see that the FAB acts as expected. If you could create a codesandbox to show the reproducible code, I could better debug it. It's hard to say with only seeing screenshots.

**Comment by shanhuiyang** [comment]
OK, I will try to repro the issue in CodeSandbox.

**Comment by dericgw** [comment]
I am going to close this for now but feel free to ping me if you can reproduce this.

**Comment by aabuhijleh** [comment]
@dericgw I could reproduce this on a very narrow width 

check https://aabuhijleh.com please

**Comment by aabuhijleh** [comment]
@shanhuiyang were you able to fix this?
