### ISSUE TITLE
SCRIPT1028: Expected identifier, string or number

### ISSUE THREAD

**Issue by sashiRachakonda** [dericgw/react-tiny-fab#45]
on Microsoft Edge the error 'SCRIPT1028: SCRIPT1028: Expected identifier, string or number' appears in the console and a blank page is rendered when just adding import { Fab, Action } from 'react-tiny-fab'; to .jsx

using Create-react-app with the latest react-scripts...here is the excerpt from package.json..

    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.3.0",
    "react-tiny-fab": "^3.2.0",

**Comment by dericgw** [comment]
See #44 and let me know if that doesn't work.

**Comment by sashiRachakonda** [comment]
that did it...thanks!
