### ISSUE TITLE
HowTo: Disable react-tiny-fab only supports up to 6 action buttons 

### ISSUE THREAD

**Issue by SylarRuby** [dericgw/react-tiny-fab#48]
I understand only 6 buttons max are supported but I needed 8. I've added 8 with css modification; works great and a super thank you for such tool.

Is there a way to disable this console log warning:

> react-tiny-fab only supports up to 6 action buttons

PS: I wish not to fork.

Thanks.

**Comment by dericgw** [comment]
If you want to submit a PR and remove the warning, I am okay with that. We can mention in the README that Material suggests not to use more than six.

**Comment by SylarRuby** [comment]
Thanks. I've found ways not to go beyond the recommended 6. Thanks for your reply.
