### ISSUE TITLE
the target undefined

### ISSUE THREAD

**Issue by anasalaqeel** [dericgw/react-tiny-fab#49]
Hi 
when I set onClick function on any component between <Fab> component I can't trigger the target 

```
function handleClick(e){
     console.log(e)
}

return(
<Fab>
<someComponentOrAction onClick={handleClick} />
</Fab>
)
```
`results in console: undefined`

how is that possible?

**Comment by dericgw** [comment]
@anasalaqeel Good catch. The event was not being passed into `onClick`. I just released `v3.4.1` which addresses that issue. Please upgrade your package version and try it out now.
