### ISSUE TITLE
Disabled Prop

### ISSUE THREAD

**Issue by papuruth** [dericgw/react-tiny-fab#54]
Is ther any way to disabled the main fab button?

**Comment by dericgw** [comment]
There is not right now but I am going to add the ability to spread props to any off the underlying components. That should add this feature. I will try and get to that by the weekend.

**Comment by dericgw** [comment]
Here is a way to achieve this. I know it's not very elegant, but it does the job. 

https://codesandbox.io/s/magical-swirles-txq1l?file=/src/App.js
