### ISSUE TITLE
MIT License page 404s

### ISSUE THREAD

**Issue by carlwood** [dericgw/react-tiny-fab#63]
- On https://dericgw.github.io/react-tiny-fab/#license-mit
- Click on 'Check it out here' 
- https://dericgw.github.io/react-tiny-fab/LICENSE.md 404s

**Comment by dericgw** [comment]
Thanks for spotting that  Do you want to submit a PR to fix it? It counts against Hacktoberfest

**Comment by osmarpetry** [comment]
Can I be assigned to this issue?

**Comment by carlwood** [comment]
@osmarpetry Yep - go for it! 👍

**Comment by dericgw** [comment]
@osmarpetry Yes, for sure.

**Comment by osmarpetry** [comment]
Pull request is open! #64
