### ISSUE TITLE
onMouseLeave cancels out onClick toggle

### ISSUE THREAD

**Issue by theFl00f** [dericgw/react-tiny-fab#65]
Current behaviour:
Even though logic exists to keep TinyFab visible when clicked, the class was being removed onMouseLeave.
Expected behaviour:
TinyFab stays visible when clicked until clicked again to allow closing.

**Comment by dericgw** [comment]
Sorry for the late response. I see that you opened a PR for this. Could you give an example of this? I started an example Codesandbox here: https://codesandbox.io/s/tender-lehmann-4hy16?file=/src/App.js

When I use the components there, they _seem_ to work as expected so I am interested in what behavior you are seeing. Thanks!

**Comment by theFl00f** [comment]
Hey friend! This is probably working as intended seeing that codepen example. The behaviour I expected was to be able to hover, as well as be able to click on the MainButton to keep the list expanded.

**Comment by dericgw** [comment]
I am not quite sure what you mean. Are you saying you want both click and hover to work at the same time?

**Comment by msagerup** [comment]
> I am not quite sure what you mean. Are you saying you want both click and hover to work at the same time?

is it possible? 

Great work btw!

**Comment by dericgw** [comment]
Currently, either is supported but not at the same time. I am going to close this for now but if more discussion is warranted, please comment and I will open this back up and consider it.
