### ISSUE TITLE
Example tap behavior stops working

### ISSUE THREAD

**Issue by cesig** [dericgw/react-tiny-fab#75]
This might not be an issue with the component, but on the example I identified buggy behavior.

If I tap the button to open the menu with the two options (= and +) and I tap =, after I tap the OK button on the Alert that it spawns and the menu closes, I am no longer able to tap the button to re-open the menu, without first de-focusing it.

I recorded a video here:
https://imgur.com/a/fITbFt3

It's a bit hard to see because I'm tapping my touch screen, but hopefully the description above explains it.

**Comment by Deep-Codes** [comment]
Seems to work fine in mine :)

**Comment by dericgw** [comment]
I tried and it worked on mine too. If this is still a problem, please comment and I will open this ticket back up.
