### ISSUE TITLE
Title text not showing when using react-router-dom Link

### ISSUE THREAD

**Issue by nonoumasy** [dericgw/react-tiny-fab#77]
Love the library. Thanks.

So when I surround the Action component with Link from react-router-dom, the title text does not show. So I tried adding an onClick handler instead but its also not working.

```
<Fab
    mainButtonStyles={{ backgroundColor: '#26978A', }}
    icon={<AddIcon />}
    alwaysShowTitle={true}
    >
    <Link
        to={{
            pathname: '/AddEvent',
            state: id,
        }}
        >
        <Action text="Add Event" style={{ backgroundColor: '#666', }}>
            <CalendarTodayOutlinedIcon />
        </Action>
    </Link>
</Fab>
```

![Screen Shot 2021-04-06 at 5 53 07 PM](https://user-images.githubusercontent.com/6312676/113795111-f7e97b00-9700-11eb-899c-c75705f7c1a6.png)

Is there an easy fix so that the text title shows? It's not a big issue but it would be nice to show the text to the User.
Here's a codeandsandbox:

https://codesandbox.io/s/dark-hooks-pzxyc?file=/src/App.js

**Comment by dericgw** [comment]
Have you tried this:

```js
<Fab
    mainButtonStyles={{ backgroundColor: '#26978A', }}
    icon={<AddIcon />}
    alwaysShowTitle={true}
    >
  <Action text="Add Event" style={{ backgroundColor: '#666', }}>
    <Link
        to={{
            pathname: '/AddEvent',
            state: id,
        }}
        >
            <CalendarTodayOutlinedIcon />
        </Link>
      </Action>
</Fab>
```
