### ISSUE TITLE
Support more than 6 buttons

### ISSUE THREAD

**Issue by lr001dev** [dericgw/react-tiny-fab#78]
I'm creating a tool bar with your library and I added one more button over 6 and the UI breaks. I understand 6 is only supported. Is it possible support than six?

**Comment by dericgw** [comment]
I am trying to follow the material guidelines, which means that six items is the limit.

![image](https://user-images.githubusercontent.com/34040106/118361704-3836e700-b552-11eb-90bc-57b58c38d273.png)

You can read more here: https://material.io/components/buttons-floating-action-button#types-of-transitions
