### ISSUE TITLE
Action Menu remains open when menu item is clicked?

### ISSUE THREAD

**Issue by sanjubhambhani** [dericgw/react-tiny-fab#79]
I just updated from v3.5.0 to v4.0.2 and noticed the action menu remains open when a menu item is clicked?

Is this by design? 

The demo on the documentation page closes as expected, which is throwing me off.

On React v17.0.2

**Comment by dericgw** [comment]
Hmmm... That's a good question. I suppose it does make sense to close it when an action button is clicked. I'll see if I can implement this.

**Comment by dericgw** [comment]
After looking through the code again, it should close when an action button is clicked as you can see here: https://github.com/dericgw/react-tiny-fab/blob/49ba6e5f88107681546720fddedb7dd76ae0ebc3/src/index.tsx#L69

Can you reproduce this?
